Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-09, with the labels that each got.

#87 Delete resources that are created during the run of example pipelines and set allowReplace of base datavolume.
  data/tekton-pipelines/okd/windows10-customize.yaml
  data/tekton-pipelines/okd/windows10-installer.yaml
Labels: lgtm, approved, dco-signoff: yes, size/M

#89 Update tekton tasks manifests to version v0.12.0
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.12.0.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.12.0.yaml
  pkg/operands/version.go
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#88 Add annotations to example pipelines datavolumes.
  data/tekton-pipelines/okd/windows10-customize.yaml
  data/tekton-pipelines/okd/windows10-installer.yaml
Labels: size/XS, lgtm, dco-signoff: yes

#86 fix the generating of junit report
  go.mod
  go.sum
  tests/tests_suite_test.go
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/kubevirt.io/client-go/LICENSE
  vendor/kubevirt.io/client-go/reporter/reporter.go
  vendor/modules.txt
Labels: lgtm, approved, dco-signoff: yes, size/XL
