Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-10, with the labels that each got.

#91 Update tekton tasks manifests to version v0.12.1
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.12.1.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.12.1.yaml
  pkg/operands/version.go
Labels: approved, dco-signoff: yes, size/XXL

#92 update golang version to 1.18 in github actions
  .github/workflows/release.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#93 add command USER 1001 to dockerfile
  Dockerfile
Labels: size/XS, lgtm, approved, dco-signoff: yes

#96 Add permissions to modify-data-object-task service account
  data/tekton-pipelines/okd/windows10-installer.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#76 Add test script which runs pipeline examples as presubmit tests.
  scripts/example-pipelines-test.sh
  scripts/test-files/configmap.yaml
  scripts/test-files/http-server.yaml
  scripts/test-files/win10-dv.yaml
  scripts/test-files/windows10-customize-pipelinerun.yaml
  scripts/test-files/windows10-installer-pipelinerun.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L

#100 Bump golang to 1.19
  .github/workflows/release.yaml
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, dco-signoff: yes, size/L

#99 Add functionality that will check if multiple CRs are deployed
  controllers/tektontasks_controller.go
  tests/tekton-tasks_test.go
  tests/tests_suite_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#101 update golang and fedora version in ci-builder dockerfile
  ci-builder/Dockerfile
Labels: size/XS, lgtm, approved, dco-signoff: yes

#103 Add 0xFelix to approvers
  OWNERS
Labels: size/XS, lgtm, approved, dco-signoff: yes
