Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-05, with the labels that each got.

#31 tekton-tasks: Add RBAC for creating pods
  config/rbac/role.yaml
  pkg/tekton-tasks/tekton-tasks.go
Labels: size/XS, lgtm, dco-signoff: yes

#30 add rest of the tasks to TTO
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/tektontasks_controller.go
  data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
  pkg/environment/environment.go
  pkg/environment/environment_test.go
  pkg/tekton-tasks/tekton-tasks.go
  pkg/tekton-tasks/tekton-tasks_test.go
  scripts/csv-generator.go
  tests/tekton-tasks_test.go
Labels: lgtm, approved, dco-signoff: yes, do-not-merge/hold, size/L

#34 Update tekton tasks manifests to version v0.9.0
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.0.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.0.yaml
  pkg/operands/version.go
Labels: approved, dco-signoff: yes, size/XXL

#36 handle object modified error in initialize steps
  controllers/tektontasks_controller.go
Labels: size/XS, lgtm, approved, dco-signoff: yes

#37 tto watches all objects it deploys
  pkg/tekton-pipelines/tekton-pipelines.go
  pkg/tekton-tasks/tekton-tasks.go
  tests/tekton-pipelines_test.go
Labels: lgtm, approved, dco-signoff: yes, size/M

#39 Fix log message when reverting changes in a pipeline
  pkg/tekton-pipelines/tekton-pipelines.go
Labels: size/XS, lgtm, dco-signoff: yes

#40 Fix usage of baseDvName and baseDvNamespace parameters
  data/tekton-pipelines/okd/windows10-installer.yaml
Labels: size/XS, lgtm, dco-signoff: yes

#38 Fix windows10-customize pipeline on kubernetes
  data/tekton-pipelines/kubernetes/windows10-customize.yaml
Labels: size/XS, lgtm, dco-signoff: yes

#41 Update tekton tasks manifests to version v0.9.1
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.1.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.1.yaml
  pkg/operands/version.go
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#43 Update tekton tasks manifests to version v0.9.2
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.2.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.2.yaml
  pkg/operands/version.go
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#46 fix security constraint for tto container
  config/manager/manager.yaml
  data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S
