Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-08, with the labels that each got.

#79 Add permissions to SA used by windows10-installer pipeline
  data/tekton-pipelines/kubernetes/windows10-installer.yaml
Labels: lgtm, dco-signoff: yes, size/M

#81 Edit tests for clusterRole and roleBinding creation
  tests/tekton-pipelines_test.go
  tests/tekton-tasks_test.go
Labels: dco-signoff: yes, size/M

#82 Delete condition that blocks creation of clusterRole and roleBinding
  pkg/tekton-pipelines/tekton-pipelines.go
Labels: size/XS, dco-signoff: yes

#83 Add permissions to pipeline SA in kubevirt-os-images namespace
  data/tekton-pipelines/okd/windows10-installer.yaml
Labels: size/XS, dco-signoff: yes

#84 enable running tests in different namespace
  tests/tests_suite_test.go
Labels: lgtm, approved, dco-signoff: yes, size/S
