Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-06, with the labels that each got.

#51 remove prometheus label and port from deploy manifest
  config/manager/manager.yaml
  data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S

#54 add pipeline service account into installer pipeline
  data/tekton-pipelines/kubernetes/windows10-installer.yaml
  data/tekton-pipelines/okd/windows10-installer.yaml
  pkg/tekton-pipelines/tekton-pipelines.go
  tests/tekton-pipelines_test.go
  tests/tekton-tasks_test.go
Labels: lgtm, approved, dco-signoff: yes, size/M

#57 update only labels and annotations in serviceAccounts in pipelines
  pkg/tekton-pipelines/tekton-pipelines.go
Labels: size/XS, lgtm, approved, dco-signoff: yes

#60 add cluster role in pipelines when deployed in ^openshift|kube namespace
  data/tekton-pipelines/okd/windows10-installer.yaml
  pkg/tekton-pipelines/tekton-pipelines.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#63 fix deploying of windows10-pipelines clusterrole
  pkg/tekton-pipelines/tekton-pipelines.go
Labels: size/XS, lgtm, approved, dco-signoff: yes

#64 Add deployment of common templates to deploy-resources.sh
  scripts/deploy-resources.sh
Labels: size/XS, lgtm, approved, dco-signoff: yes
