Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-07, with the labels that each got.

#70 Revert changes to TTO image in CSV
  data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
Labels: size/XS, lgtm, approved, dco-signoff: yes

#71 Add missing colon in DeafultCreateDataObjectIMG
  pkg/environment/environment.go
Labels: size/XS, lgtm, approved, dco-signoff: yes

#72 Improve reference pipelines
  data/tekton-pipelines/kubernetes/windows10-customize.yaml
  data/tekton-pipelines/kubernetes/windows10-installer.yaml
  data/tekton-pipelines/okd/windows10-customize.yaml
  data/tekton-pipelines/okd/windows10-installer.yaml
Labels: lgtm, approved, dco-signoff: yes, size/M

#73 Add deployment of SSP to deployment script, that is needed for run of example pipelines
  scripts/deploy-resources.sh
  scripts/ssp-sample.yaml
Labels: lgtm, approved, dco-signoff: yes, size/S
