Repository kubevirt/tekton-tasks-operator, pull requests merged in 2022-04, with the labels that each got.

#7 reenque another reconciliation, when conflict cr occures
  controllers/tektontasks_controller.go
Labels: size/XS, lgtm, approved, dco-signoff: yes

#9 add 0xFelix as a reviewer
  OWNERS
Labels: size/XS, approved, dco-signoff: yes

#8 bump tekton tasks to version v0.6.0
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.6.0.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.6.0.yaml
  pkg/operands/version.go
  pkg/tekton-tasks/tekton-tasks.go
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#1 remove runasnonroot attribute from manifests
  config/manager/manager.yaml
  data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
Labels: size/XS, approved, dco-signoff: yes

#12 Update tekton tasks manifests to version v0.7.0
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.7.0.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.7.0.yaml
  pkg/operands/version.go
Labels: approved, dco-signoff: yes, size/XXL

#14 cleanup e2e tests
  tests/tekton-pipelines_test.go
  tests/tekton-tasks_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, size/L

#15 fix deletion of resources, when TTO CR is deleted
  pkg/tekton-pipelines/tekton-pipelines.go
  pkg/tekton-tasks/tekton-tasks.go
  tests/tekton-pipelines_test.go
  tests/tekton-tasks_test.go
Labels: lgtm, approved, dco-signoff: yes, size/L

#16 update readme with better description how to deploy TTO
  README.md
Labels: lgtm, approved, dco-signoff: yes, size/S

#13 Add tests to check if tto is not deploying anything when DeployTektonTaskResouces set to false
  tests/tekton-tasks_test.go
Labels: ok-to-test, dco-signoff: yes, size/M

#18 disable devel log
  main.go
Labels: size/XS, approved, dco-signoff: yes

#17 bump golang version to 1.18
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes, size/S

#20 add update template rbac
  config/rbac/role.yaml
  pkg/tekton-tasks/tekton-tasks.go
Labels: size/XS, lgtm, approved, dco-signoff: yes

#21 Update tekton tasks manifests to version v0.8.0
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.8.0.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.8.0.yaml
  pkg/operands/version.go
Labels: lgtm, approved, dco-signoff: yes, size/XXL

#22 add ci builder image
  ci-builder/Dockerfile
Labels: lgtm, approved, dco-signoff: yes, size/S

#23 add new packages to ci builder image
  ci-builder/Dockerfile
Labels: size/XS, lgtm, approved, dco-signoff: yes

#24 add golang and which packages to ci-builder image
  ci-builder/Dockerfile
Labels: size/XS, approved, dco-signoff: yes

#26 don't generate manifest during functests
  Makefile
  ci-builder/Dockerfile
Labels: size/XS, approved, dco-signoff: yes

#27 deploy openshift version of tekton
  scripts/deploy-resources.sh
Labels: lgtm, approved, dco-signoff: yes, size/S

#19 Remove 'oc new-project tekton-pipelines' from deployment script
  scripts/deploy-resources.sh
Labels: dco-signoff: yes, size/S
